# Text behind the #-sign is not evaluated as code by R. 
# This is useful, because it allows you to add comments explaining what the script does.

# In this script, replace the ... with the appropriate commands.

x1 = ...
x2 = ...
x3 = ...
t = ...
plot(...)
